### ISSUE TITLE
rpm macro

### ISSUE THREAD

**Issue by mslacken** [openSUSE/obs-scm-bridge#4]
The 
```
Source0: FOO.tar.gz
```
makes trouble as for the scm bridge, the sources are already unpacked. So it would be useful to have something like
```
%if ! %{?obs_scm:0}
Source0: FOO.tar.gz
%endif

**Comment by mslacken** [comment]
Perhaps the first command was misleading, I meant something more like
```
%if 0%{?obs_scm}
Source:  https://github.com/baar/foo/releases/download/v%{version}/foo-%{version}.tar.gz 
%else
Source: foo-%{version}.tar,gz
%

**Comment by adrianschroeter** [comment]
Why is using an asset not option here?

#!RemoteAssetUrl: git+https://github.com/atomgomba/orangebox#v0.2.0
Source:         orangebox-%{version}.tar.gz

**Comment by mlschroe** [comment]
Do you mean:
```
#!RemoteAsset
Source:  https://github.com/baar/foo/releases/download/v%{version}/foo-%{version}.tar.gz 
```

What exactly does not work?

**Comment by mslacken** [comment]
I did not know of the `#! RemoteAsset` flag. 
With it this flag the build fails at the `srpm` creation as the tar ball is missing.

**Comment by mcepl** [comment]
What is the status of this ticket? Yes, `Source` tag should probably be not included at all, but shouldn’ŧ this be closed?

**Comment by adrianschroeter** [comment]
Yes, it is not really a bridge topic, more a research project how to package from git using rpm spec files..
