### ISSUE TITLE
Please tag 4ac1b2d9ce256a79aa5475521c5e6b48d15d931d as 0.2.1

### ISSUE THREAD

**Issue by dcermak** [openSUSE/obs-scm-bridge#7]
https://build.opensuse.org/package/show/openSUSE:Tools/obs-scm-bridge has version 0.2.1 but none such tag exists in git. The changelog indicates that 4ac1b2d9ce256a79aa5475521c5e6b48d15d931d is probably 0.2.1. Could you please tag it?

**Comment by adrianschroeter** [comment]
I forgot to push --tags ....
